### ISSUE TITLE
Preprocess field

### ISSUE THREAD

**Issue by cuihtlauac** [janestreet/ppx_stable#3]
It would be nice to be able to write something like this:
```ocaml
type raw = {
  title : string;
  md : string;
}
type doc = {
  title : string;
  slug : string;
  md : string;
  html : string;
} [@@deriving stable_record ~version:raw ~preprocess:[(slug, title, to_slug); (html, md, to_html)])
```

Where `to_slug` and `to_html` both are functions of type `string -> string`

**Comment by neojski** [comment]
Could you spell out the code that you'd like `ppx_stable` to generate in this case? I'm not sure I understand the proposal.

**Comment by cuihtlauac** [comment]
Hi @neojski,

I'd like the function `doc_of_raw` to look like that:
```ocaml
let doc_of_raw ({ title; md } : raw) = {
    title;
    md;
    slug = to_slug title;
    html = to_html md;
}
```

The function `doc_to_raw` would be defined the same as it by:
```ocaml
[@@deriving stable_record ~version:raw ~remove:[slug; html]]
```

**Comment by neojski** [comment]
Does this work for you?

```ocaml
type raw =
  { title : string
  ; md : string
  }

type doc =
  { title : string
  ; slug : string
  ; md : string
  ; html : string
  }
[@@deriving stable_record ~version:raw ~remove:[ html; slug ]]

let doc_of_raw ~to_html ~to_slug t =
  doc_of_raw ~html:(to_html t.md) ~slug:(to_slug t.title) t
;;
```

**Comment by cuihtlauac** [comment]
You are right, it would work. But in my case I'd inline the calls to `to_html` and `to_slug`:
```ocaml
let doc_of_raw t =
  doc_of_raw ~html:(to_html t.md) ~slug:(to_slug t.title) t
;;
```
I don't need to pass them whenever building a `doc`; those functions are always the same. 

As a side note, I realize that this feature is actually a generalization of what I'm requesting in https://github.com/janestreet/ppx_stable/issues/2. It could be used to handle renamings by using `Fun.id`:
```ocaml
[@@deriving stable_record ~version:person ~preprocess:[(given, first, Fun.id); (family, last, Fun.id) ~remove:[ given, family ]])
```

**Comment by neojski** [comment]
I think that `preprocess` is not worth it: we'd end up with a 3-tuple arguments with names from both records which essentially means that it's impossible to understand what code this is going to generate without looking at the documentation or the generated code.

Is the proposed solution for this sufficient for your use-case?

**Comment by neojski** [comment]
I'll close this for the reason in the last comment: it would be difficult to understand what this function does and I'd like this ppx to stay as simple and self-explanatory. as I mentioned, I'm more open to the renaming fields proposal.

However, feel free to reopen if you'd like to chat about this further!
